import type { CardDefinition, CardInstance } from './types.js'

export const CARD_DEFINITIONS: CardDefinition[] = [
  {
    id: 'hidden',
    name: 'Hidden Card',
    type: 'MOVEMENT',
    movementType: 'WILD',
    movementValue: 1,
    goldValue: 1,
    purchaseCost: 3,
  },
  {
    id: 'explorer',
    name: 'Explorer',
    type: 'MOVEMENT',
    movementType: 'GREEN',
    movementValue: 2,
    goldValue: 1,
    purchaseCost: 2,
  },
  {
    id: 'herbalist',
    name: 'Herbalist',
    type: 'MOVEMENT',
    movementType: 'GREEN',
    movementValue: 3,
    goldValue: 1,
    purchaseCost: 4,
  },
  {
    id: 'scout',
    name: 'Scout',
    type: 'MOVEMENT',
    movementType: 'GREEN',
    movementValue: 4,
    goldValue: 1,
    purchaseCost: 6,
  },
  {
    id: 'ranger',
    name: 'Ranger',
    type: 'MOVEMENT',
    movementType: 'GREEN',
    movementValue: 5,
    goldValue: 1,
    purchaseCost: 8,
  },
  {
    id: 'pathfinder',
    name: 'Pathfinder',
    type: 'MOVEMENT',
    movementType: 'GREEN',
    movementValue: 6,
    goldValue: 1,
    purchaseCost: 10,
  },
  {
    id: 'sailor',
    name: 'Sailor',
    type: 'MOVEMENT',
    movementType: 'BLUE',
    movementValue: 2,
    goldValue: 1,
    purchaseCost: 2,
  },
  {
    id: 'seasoned_sailor',
    name: 'Seasoned Sailor',
    type: 'MOVEMENT',
    movementType: 'BLUE',
    movementValue: 3,
    goldValue: 1,
    purchaseCost: 4,
  },
  {
    id: 'navigator',
    name: 'Navigator',
    type: 'MOVEMENT',
    movementType: 'BLUE',
    movementValue: 3,
    goldValue: 2,
    purchaseCost: 5,
  },
  {
    id: 'captain',
    name: 'Captain',
    type: 'MOVEMENT',
    movementType: 'BLUE',
    movementValue: 4,
    goldValue: 2,
    purchaseCost: 6,
  },
  {
    id: 'admiral',
    name: 'Admiral',
    type: 'MOVEMENT',
    movementType: 'BLUE',
    movementValue: 5,
    goldValue: 2,
    purchaseCost: 7,
  },
  {
    id: 'coin',
    name: 'Coin',
    type: 'MOVEMENT',
    movementType: 'YELLOW',
    movementValue: 2,
    goldValue: 2,
    purchaseCost: 2,
  },
  {
    id: 'trader',
    name: 'Trader',
    type: 'MOVEMENT',
    movementType: 'YELLOW',
    movementValue: 4,
    goldValue: 2,
    purchaseCost: 5,
  },
  {
    id: 'treasurer',
    name: 'Treasurer',
    type: 'MOVEMENT',
    movementType: 'YELLOW',
    movementValue: 2,
    goldValue: 4,
    purchaseCost: 5,
  },
  {
    id: 'master_trader',
    name: 'Master Trader',
    type: 'MOVEMENT',
    movementType: 'YELLOW',
    movementValue: 3,
    goldValue: 3,
    purchaseCost: 6,
  },
  {
    id: 'caravan',
    name: 'Caravan',
    type: 'MOVEMENT',
    movementType: 'YELLOW',
    movementValue: 4,
    goldValue: 4,
    purchaseCost: 8,
  },
  {
    id: 'adventurer',
    name: 'Adventurer',
    type: 'MOVEMENT',
    movementType: 'WILD',
    movementValue: 2,
    goldValue: 1,
    purchaseCost: 5,
  },
  {
    id: 'trailblazer',
    name: 'Trailblazer',
    type: 'MOVEMENT',
    movementType: 'WILD',
    movementValue: 3,
    goldValue: 1,
    purchaseCost: 7,
  },
  {
    id: 'wayfarer',
    name: 'Wayfarer',
    type: 'MOVEMENT',
    movementType: 'WILD',
    movementValue: 4,
    goldValue: 1,
    purchaseCost: 9,
  },
  {
    id: 'shortcut_map',
    name: 'Shortcut Map',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 5,
    actionEffect: 'MAP_SHORTCUT',
    actionCategory: 'SPELL',
  },
  {
    id: 'second_wind',
    name: 'Second Wind',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 4,
    actionEffect: 'SECOND_WIND',
    actionCategory: 'SPELL',
  },
  {
    id: 'merchant_caravan',
    name: 'Merchant Caravan',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 5,
    actionEffect: 'MERCHANT_CARAVAN',
    actionCategory: 'SPELL',
  },
  {
    id: 'steal_plans',
    name: 'Steal Plans',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 6,
    actionEffect: 'STEAL_PLANS',
    actionCategory: 'CURSE',
  },
  {
    id: 'guide',
    name: 'Guide',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 5,
    actionEffect: 'GUIDE',
    actionCategory: 'SPELL',
  },
  {
    id: 'phase_walk',
    name: 'Phase Walk',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 5,
    actionEffect: 'PHASE_WALK',
    actionCategory: 'SPELL',
  },
  {
    id: 'reshuffle_hand',
    name: 'Reshuffle Hand',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 5,
    actionEffect: 'RESHUFFLE_HAND',
    actionCategory: 'SPELL',
  },
  {
    id: 'echo_power',
    name: 'Echo Power',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 6,
    actionEffect: 'ECHO_POWER',
    actionCategory: 'SPELL',
  },
  {
    id: 'protective_circle',
    name: 'Protective Circle',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 5,
    actionEffect: 'PROTECTIVE_CIRCLE',
    actionCategory: 'SPELL',
  },
  {
    id: 'path_fracture',
    name: 'Path Fracture',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 5,
    actionEffect: 'PATH_FRACTURE',
    actionCategory: 'CURSE',
  },
  {
    id: 'fog_of_forgetting',
    name: 'Fog of Forgetting',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 5,
    actionEffect: 'FOG_OF_FORGETTING',
    actionCategory: 'CURSE',
  },
  {
    id: 'poverty_curse',
    name: 'Poverty Curse',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 5,
    actionEffect: 'POVERTY_CURSE',
    actionCategory: 'CURSE',
  },
  {
    id: 'tangled_roots',
    name: 'Tangled Roots',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 5,
    actionEffect: 'TANGLED_ROOTS',
    actionCategory: 'CURSE',
  },
  {
    id: 'closed_market',
    name: 'Closed Market',
    type: 'ACTION',
    movementType: 'WILD',
    movementValue: 0,
    goldValue: 0,
    purchaseCost: 6,
    actionEffect: 'CLOSED_MARKET',
    actionCategory: 'CURSE',
  },
]

export const CARD_BY_ID = Object.fromEntries(
  CARD_DEFINITIONS.map((card) => [card.id, card]),
) as Record<string, CardDefinition>

export const STARTING_DECK: Array<{ cardId: string; count: number }> = [
  { cardId: 'explorer', count: 4 },
  { cardId: 'sailor', count: 1 },
  { cardId: 'coin', count: 3 },
]

export const MARKET_CARD_IDS = [
  'herbalist',
  'scout',
  'ranger',
  'pathfinder',
  'seasoned_sailor',
  'navigator',
  'captain',
  'admiral',
  'trader',
  'treasurer',
  'master_trader',
  'caravan',
  'adventurer',
  'trailblazer',
  'wayfarer',
  'shortcut_map',
  'second_wind',
  'merchant_caravan',
  'steal_plans',
  'guide',
  'phase_walk',
  'reshuffle_hand',
  'echo_power',
  'protective_circle',
  'path_fracture',
  'fog_of_forgetting',
  'poverty_curse',
  'tangled_roots',
  'closed_market',
]

export const ACTION_CARD_IDS = MARKET_CARD_IDS.filter(
  (cardId) => CARD_BY_ID[cardId]?.type === 'ACTION',
)

export const createCardInstance = (
  cardId: string,
  instanceId: string,
): CardInstance => ({
  cardId,
  instanceId,
})
