import type { CardDefinition, CardInstance } from './types.js'

export const CARD_DEFINITIONS: CardDefinition[] = [
  {
    id: 'hidden',
    name: 'Hidden Card',
    type: 'MOVEMENT',
    movementType: 'WILD',
    movementValue: 1,
    goldValue: 1,
    purchaseCost: 3,
  },
  {
    id: 'explorer',
    name: 'Explorer',
    type: 'MOVEMENT',
    movementType: 'GREEN',
    movementValue: 2,
    goldValue: 1,
    purchaseCost: 2,
  },
  {
    id: 'herbalist',
    name: 'Herbalist',
    type: 'MOVEMENT',
    movementType: 'GREEN',
    movementValue: 3,
    goldValue: 1,
    purchaseCost: 4,
  },
  {
    id: 'scout',
    name: 'Scout',
    type: 'MOVEMENT',
    movementType: 'GREEN',
    movementValue: 4,
    goldValue: 1,
    purchaseCost: 6,
  },
  {
    id: 'ranger',
    name: 'Ranger',
    type: 'MOVEMENT',
    movementType: 'GREEN',
    movementValue: 5,
    goldValue: 1,
    purchaseCost: 8,
  },
  {
    id: 'pathfinder',
    name: 'Pathfinder',
    type: 'MOVEMENT',
    movementType: 'GREEN',
    movementValue: 6,
    goldValue: 1,
    purchaseCost: 10,
  },
  {
    id: 'sailor',
    name: 'Sailor',
    type: 'MOVEMENT',
    movementType: 'BLUE',
    movementValue: 2,
    goldValue: 1,
    purchaseCost: 2,
  },
  {
    id: 'seasoned_sailor',
    name: 'Seasoned Sailor',
    type: 'MOVEMENT',
    movementType: 'BLUE',
    movementValue: 3,
    goldValue: 1,
    purchaseCost: 4,
  },
  {
    id: 'navigator',
    name: 'Navigator',
    type: 'MOVEMENT',
    movementType: 'BLUE',
    movementValue: 3,
    goldValue: 2,
    purchaseCost: 5,
  },
  {
    id: 'captain',
    name: 'Captain',
    type: 'MOVEMENT',
    movementType: 'BLUE',
    movementValue: 4,
    goldValue: 2,
    purchaseCost: 6,
  },
  {
    id: 'admiral',
    name: 'Admiral',
    type: 'MOVEMENT',
    movementType: 'BLUE',
    movementValue: 5,
    goldValue: 2,
    purchaseCost: 7,
  },
  {
    id: 'coin',
    name: 'Coin',
    type: 'MOVEMENT',
    movementType: 'YELLOW',
    movementValue: 2,
    goldValue: 2,
    purchaseCost: 2,
  },
  {
    id: 'trader',
    name: 'Trader',
    type: 'MOVEMENT',
    movementType: 'YELLOW',
    movementValue: 4,
    goldValue: 2,
    purchaseCost: 5,
  },
  {
    id: 'treasurer',
    name: 'Treasurer',
    type: 'MOVEMENT',
    movementType: 'YELLOW',
    movementValue: 2,
    goldValue: 4,
    purchaseCost: 5,
  },
  {
    id: 'master_trader',
    name: 'Master Trader',
    type: 'MOVEMENT',
    movementType: 'YELLOW',
    movementValue: 3,
    goldValue: 3,
    purchaseCost: 6,
  },
  {
    id: 'caravan',
    name: 'Caravan',
    type: 'MOVEMENT',
    movementType: 'YELLOW',
    movementValue: 4,
    goldValue: 4,
    purchaseCost: 8,
  },
  {
    id: 'adventurer',
    name: 'Adventurer',
    type: 'MOVEMENT',
    movementType: 'WILD',
    movementValue: 2,
    goldValue: 1,
    purchaseCost: 5,
  },
  {
    id: 'trailblazer',
    name: 'Trailblazer',
    type: 'MOVEMENT',
    movementType: 'WILD',
    movementValue: 3,
    goldValue: 1,
    purchaseCost: 7,
  },
  {
    id: 'wayfarer',
    name: 'Wayfarer',
    type: 'MOVEMENT',
    movementType: 'WILD',
    movementValue: 4,
    goldValue: 1,
    purchaseCost: 9,
  },
]

export const CARD_BY_ID = Object.fromEntries(
  CARD_DEFINITIONS.map((card) => [card.id, card]),
) as Record<string, CardDefinition>

export const STARTING_DECK: Array<{ cardId: string; count: number }> = [
  { cardId: 'explorer', count: 4 },
  { cardId: 'sailor', count: 1 },
  { cardId: 'coin', count: 3 },
]

export const MARKET_CARD_IDS = [
  'herbalist',
  'scout',
  'ranger',
  'pathfinder',
  'seasoned_sailor',
  'navigator',
  'captain',
  'admiral',
  'trader',
  'treasurer',
  'master_trader',
  'caravan',
  'adventurer',
  'trailblazer',
  'wayfarer',
]

export const createCardInstance = (
  cardId: string,
  instanceId: string,
): CardInstance => ({
  cardId,
  instanceId,
})
