export const EVENTS = {
  sessionUpdate: 'session:update',
  roomCreate: 'room:create',
  roomJoin: 'room:join',
  roomLeave: 'room:leave',
  roomUpdate: 'room:update',
  roomUpdateSettings: 'room:update-settings',
  roomUpdateAppearance: 'room:update-appearance',
  roomUpdatePlayerName: 'room:update-player-name',
  roomReorderPlayers: 'room:reorder-players',
  roomAddBot: 'room:add-bot',
  roomRemoveBot: 'room:remove-bot',
  gameStart: 'game:start',
  gameChooseStart: 'game:choose-start',
  gameState: 'game:state',
  gamePlayCard: 'game:play-card',
  gameUseActionCard: 'game:use-action-card',
  gameDiscardCard: 'game:discard-card',
  gameMove: 'game:move',
  gameBuyCard: 'game:buy-card',
  gameUseToken: 'game:use-token',
  gameEndTurn: 'game:end-turn',
  gameError: 'game:error',
} as const
